version: "3"
services:
  redis-master1:
    image: redis:5.0 # 基础镜像
    container_name: node1 # 容器名称
    working_dir: /config # 切换工作目录
    environment: # 环境变量
      - PORT=6391 # 会使用config/nodes-${PORT}.conf这个配置文件
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports: # 映射端口，对外提供服务
      - 6391:6391 # redis的服务端口
      - 16391:16391 # redis集群监控端口
    stdin_open: true # 标准输入打开
    tty: true # 后台运行不退出
    #network_mode: host # 使用host模式
    privileged: true # 拥有容器内命令执行的权限
    volumes:
      - ./config:/config #配置文件目录映射到宿主机
    entrypoint: # 设置服务默认的启动程序
      - /bin/bash
      - redis.sh
  redis-master2:
    image: redis:5.0
    working_dir: /config
    container_name: node2
    environment:
      - PORT=6392
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - 6392:6392
      - 16392:16392
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - ./config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-master3:
    image: redis:5.0
    container_name: node3
    working_dir: /config
    environment:
      - PORT=6393
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - 6393:6393
      - 16393:16393
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - ./config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave1:
    image: redis:5.0
    container_name: node4
    working_dir: /config
    environment:
      - PORT=6394
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - 6394:6394
      - 16394:16394
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - ./config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave2:
    image: redis:5.0
    working_dir: /config
    container_name: node5
    environment:
      - PORT=6395
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - 6395:6395
      - 16395:16395
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - ./config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
  redis-slave3:
    image: redis:5.0
    container_name: node6
    working_dir: /config
    environment:
      - PORT=6396
      - TZ=Asia/Shanghai
      - LANG=en_US.UTF-8
    ports:
      - 6396:6396
      - 16396:16396
    stdin_open: true
    #network_mode: host
    tty: true
    privileged: true
    volumes:
      - ./config:/config
    entrypoint:
      - /bin/bash
      - redis.sh
      
# 查询docker容器ip
# docker inspect --format='{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)
# 组建集群(注意ip和端口)
# redis-cli -h 172.20.0.5 -p 7001 --cluster create 172.20.0.2:6395 172.20.0.3:6396 172.20.0.4:6394 172.20.0.5:6391 172.20.0.6:6393 172.20.0.7:6392 --cluster-replicas 1


